let tittle=document.getElementById("tittle")
// let testText1= tittle.innerText;
// let testText2=tittle.textContent; // 👀🚨👀 It wil show the hidden text as well 
// console.log(testText1);
// console.log(testText2);   

// let testText3= tittle.innerHTML;   // 👀👀🙇‍♂️ Show all inner content inside the tag(also inner tag)
// console.log(testText3);

let heading=document.getElementsByClassName("heading"); // 🙇‍♂️👀👀 Show HTML Collection
console.log(heading);


// 🙇‍♂️🙇‍♂️👀 Converting the NodeList/ HTML Collection into an Array
//  Array.from(NodeList/HTML Collection)